#!/bin/bash

# Supercopy script for dotfiles.
# I do not like keeping dotfiles literally in my revision system.
# Whenever I do a fresh install, most of the trash in dots is being removed.

# run as ./super; will copy dotfiles to <here>.

# COLCONST
RED='\033[0;31m'
GRE='\033[0;32m'
PUR='\033[0;35m'
NC='\033[0m'

# SYSCONST
REPO='https://github.com/duraki/dotfiles'
REPOSYS=$(pwd)

# Dotfiles
TMUX_CONF_LOC=~/.config/.tmux.conf
GTK3_CONF_LOC=~/.config/gtk-3.0/gtk.css
ZSHRC_CONF_LOC=~/.zshrc
ALIAS_CONF_LOC=~/.config/aliases

XFCE_DIR_LOC=~/.config/xfce4

copy() {
    echo -e "${GRE}Copying from $1 to $2 ..."
    cp -R $1 $2
}

copy $TMUX_CONF_LOC $REPOSYS
copy $GTK3_CONF_LOC $REPOSYS
copy $ALIAS_CONF_LOC $REPOSYS
copy $ZSHRC_CONF_LOC $REPOSYS
copy $XFCE_DIR_LOC $REPOSYS

echo -e "\n${NC}All done! ${PUR}Check: $REPO"
